workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter version
        script: |
          flutter --version
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run Flutter analyzer
        script: |
          flutter analyze
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

